[
    {
        "tab": "Smileys",
        "icon": "emoticon",
        "emoji": [{"name":"grinning", "symbol":"😀"},
            {"name":"grin", "symbol":"😁"},
            {"name":"joy", "symbol":"😂"},
            {"name":"rolling_on_the_floor_laughing", "symbol":"🤣"},
            {"name":"sunglasses", "symbol":"😎"},
            {"name":"yum", "symbol":"😋"},
            {"name":"kissing_heart", "symbol":"😘"},
            {"name":"hugging_face", "symbol":"🤗"},
            {"name":"hankey", "symbol":"💩"},
            {"name":"see_no_evil", "symbol":"🙈"},
            {"name":"hear_no_evil", "symbol":"🙉"},
            {"name":"speak_no_evil", "symbol":"🙊"},
            {"name":"muscle", "symbol":"💪"},
            {"name":"point_left", "symbol":"👈"},
            {"name":"point_right", "symbol":"👉"},
            {"name":"point_up", "symbol":"☝"},
            {"name":"middle_finger", "symbol":"🖕"},
            {"name":"v", "symbol":"✌"},
            {"name":"ok_hand", "symbol":"👌"},
            {"name":"wave", "symbol":"👋"}
        ]
    },
    {
        "tab": "Nature",
        "icon": "cat",
        "emoji": [
            {"name":"monkey_face", "symbol":"🐵"},
            {"name":"fox_face", "symbol":"🦊"},
            {"name":"wolf", "symbol":"🐺"},
            {"name":"pig", "symbol":"🐷"},
            {"name":"lion_face", "symbol":"🦁"},
            {"name":"unicorn_face", "symbol":"🦄"},
            {"name":"water_buffalo", "symbol":"🐃"},
            {"name":"rabbit", "symbol":"🐰"},
            {"name":"rooster", "symbol":"🐓"},
            {"name":"eagle", "symbol":"🦅"},
            {"name":"crocodile", "symbol":"🐊"},
            {"name":"dragon_face", "symbol":"🐲"},
            {"name":"butterfly", "symbol":"🦋"},
            {"name":"beetle", "symbol":"🐞"},
            {"name":"tulip", "symbol":"🌷"},
            {"name":"rose", "symbol":"🌹"}
        ]
    },
    {
        "tab": "Food & Drink",
        "icon": "food",
        "emoji": [
            {"name":"grapes", "symbol":"🍇"},
            {"name":"watermelon", "symbol":"🍉"},
            {"name":"tangerine", "symbol":"🍊"},
            {"name":"lemon", "symbol":"🍋"},
            {"name":"banana", "symbol":"🍌"},
            {"name":"apple", "symbol":"🍎"},
            {"name":"cherries", "symbol":"🍒"},
            {"name":"pineapple", "symbol":"🍍"},
            {"name":"corn", "symbol":"🌽"},
            {"name":"hot_pepper", "symbol":"🌶"},
            {"name":"cheese_wedge", "symbol":"🧀"},
            {"name":"pizza", "symbol":"🍕"},
            {"name":"burrito", "symbol":"🌯"},
            {"name":"doughnut", "symbol":"🍩"},
            {"name":"beer", "symbol":"🍺"},
            {"name":"champagne", "symbol":"🍾"}
        ]
    },
    {
        "tab": "Activities",
        "icon": "football-australian",
        "emoji": [
            {"name":"jack_o_lantern", "symbol":"🎃"},
            {"name":"christmas_tree", "symbol":"🎄"},
            {"name":"boxing_glove", "symbol":"🥊"},
            {"name":"ball", "symbol":"🎱"},
            {"name":"soccer", "symbol":"⚽"},
            {"name":"volleyball", "symbol":"🏐"},
            {"name":"football", "symbol":"🏈"},
            {"name":"video_game", "symbol":"🎮"},
            {"name":"hearts", "symbol":"♥"},
            {"name":"diamonds", "symbol":"♦"},
            {"name":"clubs", "symbol":"♣"},
            {"name":"spades", "symbol":"♠"},
        ]
    },
    {
        "tab": "Flags",
        "icon": "flag",
        "emoji": [
            {"name":"flag-pl", "char":"🇵🇱"},
            {"name":"flag-ac", "symbol":"🇦🇨"},
            {"name":"flag-ad", "symbol":"🇦🇩"},
            {"name":"flag-ao", "symbol":"🇦🇴"},
            {"name":"flag-af", "symbol":"🇦🇫"},
            {"name":"flag-ag", "symbol":"🇦🇬"},
            {"name":"flag-am", "symbol":"🇦🇲"},
            {"name":"flag-aq", "symbol":"🇦🇶"},
            {"name":"flag-ar", "symbol":"🇦🇷"},
            {"name":"flag-bg", "symbol":"🇧🇬"},
            {"name":"flag-be", "symbol":"🇧🇪"},
            {"name":"flag-br", "symbol":"🇧🇷"},
            {"name":"de", "symbol":"🇩🇪"},
            {"name":"flag-eu", "symbol":"🇪🇺"},
            {"name":"flag-ua", "symbol":"🇺🇦"},
            {"name":"flag-um", "symbol":"🇺🇲"},
            {"name":"flag-tr", "symbol":"🇹🇷"},
            {"name":"es", "symbol":"🇪🇸"},
            {"name":"cn", "symbol":"🇨🇳"},
            {"name":"flag-by", "symbol":"🇧🇾"},
            {"name":"flag-nl", "char":"🇳🇱"},
            {"name":"gb", "char":"🇬🇧"},
            {"name":"flag-ch", "char":"🇨🇭"},
            {"name":"flag-bg", "symbol":"🇧🇬"}
        ]
    }
]
