[
    {
        "tab": "Smileys",
        "icon": "emoticon",
        "emoji": [{"name":"grinning", "char":"😀"},
            {"name":"grin", "char":"😁"},
            {"name":"joy", "char":"😂"},
            {"name":"rolling_on_the_floor_laughing", "char":"🤣"},
            {"name":"sunglasses", "char":"😎"},
            {"name":"yum", "char":"😋"},
            {"name":"kissing_heart", "char":"😘"},
            {"name":"hugging_face", "char":"🤗"},
            {"name":"hankey", "char":"💩"},
            {"name":"see_no_evil", "char":"🙈"},
            {"name":"hear_no_evil", "char":"🙉"},
            {"name":"speak_no_evil", "char":"🙊"},
            {"name":"muscle", "char":"💪"},
            {"name":"point_left", "char":"👈"},
            {"name":"point_right", "char":"👉"},
            {"name":"point_up", "char":"☝"},
            {"name":"point_up_2", "char":"👆"},
            {"name":"middle_finger", "char":"🖕"},
            {"name":"v", "char":"✌"},
            {"name":"ok_hand", "char":"👌"},
            {"name":"wave", "char":"👋"}
        ]
    },
    {
        "tab": "Nature",
        "icon": "cat",
        "emoji": [
            {"name":"monkey_face", "char":"🐵"},
            {"name":"monkey", "char":"🐒"},
            {"name":"fox_face", "char":"🦊"},
            {"name":"wolf", "char":"🐺"},
            {"name":"pig", "char":"🐷"},
            {"name":"lion_face", "char":"🦁"},
            {"name":"unicorn_face", "char":"🦄"},
            {"name":"water_buffalo", "char":"🐃"},
            {"name":"rabbit", "char":"🐰"},
            {"name":"rooster", "char":"🐓"},
            {"name":"eagle", "char":"🦅"},
            {"name":"crocodile", "char":"🐊"},
            {"name":"dragon_face", "char":"🐲"},
            {"name":"butterfly", "char":"🦋"},
            {"name":"beetle", "char":"🐞"},
            {"name":"tulip", "char":"🌷"},
            {"name":"rose", "char":"🌹"}
        ]
    },
    {
        "tab": "Food & Drink",
        "icon": "food",
        "emoji": [
            {"name":"grapes", "char":"🍇"},
            {"name":"melon", "char":"🍈"},
            {"name":"watermelon", "char":"🍉"},
            {"name":"tangerine", "char":"🍊"},
            {"name":"lemon", "char":"🍋"},
            {"name":"banana", "char":"🍌"},
            {"name":"apple", "char":"🍎"},
            {"name":"cherries", "char":"🍒"},
            {"name":"pineapple", "char":"🍍"},
            {"name":"corn", "char":"🌽"},
            {"name":"hot_pepper", "char":"🌶"},
            {"name":"cheese_wedge", "char":"🧀"},
            {"name":"pizza", "char":"🍕"},
            {"name":"burrito", "char":"🌯"},
            {"name":"doughnut", "char":"🍩"},
            {"name":"beer", "char":"🍺"},
            {"name":"champagne", "char":"🍾"}
        ]
    },
    {
        "tab": "Activities",
        "icon": "football-australian",
        "emoji": [
            {"name":"jack_o_lantern", "char":"🎃"},
            {"name":"christmas_tree", "char":"🎄"},
            {"name":"boxing_glove", "char":"🥊"},
            {"name":"ball", "char":"🎱"},
            {"name":"soccer", "char":"⚽"},
            {"name":"volleyball", "char":"🏐"},
            {"name":"football", "char":"🏈"},
            {"name":"ribbon", "char":"🎀"},
            {"name":"video_game", "char":"🎮"},
            {"name":"hearts", "char":"♥"},
            {"name":"diamonds", "char":"♦"},
            {"name":"clubs", "char":"♣"},
            {"name":"spades", "char":"♠"},
            {"name":"black_joker", "char":"🃏"}
        ]
    },
    {
        "tab": "Flags",
        "icon": "flag",
        "emoji": [
            {"name":"flag-ac", "char":"🇦🇨"},
            {"name":"flag-ad", "char":"🇦🇩"},
            {"name":"flag-ao", "char":"🇦🇴"},
            {"name":"flag-af", "char":"🇦🇫"},
            {"name":"flag-ag", "char":"🇦🇬"},
            {"name":"flag-am", "char":"🇦🇲"},
            {"name":"flag-ao", "char":"🇦🇴"},
            {"name":"flag-aq", "char":"🇦🇶"},
            {"name":"flag-ar", "char":"🇦🇷"},
            {"name":"flag-bg", "char":"🇧🇬"},
            {"name":"flag-be", "char":"🇧🇪"},
            {"name":"flag-br", "char":"🇧🇷"},
            {"name":"flag-eu", "char":"🇪🇺"},
            {"name":"flag-ua", "char":"🇺🇦"},
            {"name":"flag-um", "char":"🇺🇲"},
            {"name":"flag-tr", "char":"🇹🇷"},
            {"name":"es", "char":"🇪🇸"},
            {"name":"cn", "char":"🇨🇳"},
            {"name":"flag-by", "char":"🇧🇾"},
            {"name":"flag-bg", "char":"🇧🇬"}
        ]
    }
]
